//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lavest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lavest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _14359043_523354901190423_6594095113657359987_n {
            get {
                object obj = ResourceManager.GetObject("14359043_523354901190423_6594095113657359987_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _145719b77ubudiu0o7ody0 {
            get {
                object obj = ResourceManager.GetObject("145719b77ubudiu0o7ody0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _17_512 {
            get {
                object obj = ResourceManager.GetObject("17-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _17445b84_0268_4e61_8087_bd6e2ce4fc95 {
            get {
                object obj = ResourceManager.GetObject("17445b84-0268-4e61-8087-bd6e2ce4fc95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _6a0120a9370e90970b014e5f81703d970c_800wi {
            get {
                object obj = ResourceManager.GetObject("6a0120a9370e90970b014e5f81703d970c-800wi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _as {
            get {
                object obj = ResourceManager.GetObject("as", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add_people_1 {
            get {
                object obj = ResourceManager.GetObject("add_people_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adduser_4961 {
            get {
                object obj = ResourceManager.GetObject("adduser_4961", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap adduser_49611 {
            get {
                object obj = ResourceManager.GetObject("adduser_49611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap asd {
            get {
                object obj = ResourceManager.GetObject("asd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bars_chart_ascending_icon_icons {
            get {
                object obj = ResourceManager.GetObject("bars-chart-ascending_icon-icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bir {
            get {
                object obj = ResourceManager.GetObject("bir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Birthday_80_icon_icons_com_57369 {
            get {
                object obj = ResourceManager.GetObject("Birthday-80_icon-icons.com_57369", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bot_sair {
            get {
                object obj = ResourceManager.GetObject("bot_sair", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bot_sair1 {
            get {
                object obj = ResourceManager.GetObject("bot_sair1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar_clock_icon_34472 {
            get {
                object obj = ResourceManager.GetObject("calendar-clock-icon_34472", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cart_add_icon {
            get {
                object obj = ResourceManager.GetObject("cart-add-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap consultas_icon_color {
            get {
                object obj = ResourceManager.GetObject("consultas-icon-color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Crystal_Clear_action_exit_svg {
            get {
                object obj = ResourceManager.GetObject("Crystal_Clear_action_exit.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Custom_Icon_Design_Pretty_Office_8_Accept {
            get {
                object obj = ResourceManager.GetObject("Custom-Icon-Design-Pretty-Office-8-Accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Custom_Icon_Design_Pretty_Office_9_Edit_validated {
            get {
                object obj = ResourceManager.GetObject("Custom-Icon-Design-Pretty-Office-9-Edit-validated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_search_flat {
            get {
                object obj = ResourceManager.GetObject("document-search-flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap facce {
            get {
                object obj = ResourceManager.GetObject("facce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_customer_29180 {
            get {
                object obj = ResourceManager.GetObject("folder-customer-29180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_vectors_icon {
            get {
                object obj = ResourceManager.GetObject("folder-vectors-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap frete {
            get {
                object obj = ResourceManager.GetObject("frete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funcionario {
            get {
                object obj = ResourceManager.GetObject("funcionario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funcionario1 {
            get {
                object obj = ResourceManager.GetObject("funcionario1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gestao_de_estoqu {
            get {
                object obj = ResourceManager.GetObject("gestao-de-estoqu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grafico_ascendente_de_um_empresario_318_62626 {
            get {
                object obj = ResourceManager.GetObject("grafico-ascendente-de-um-empresario_318-62626", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_ecommerce {
            get {
                object obj = ResourceManager.GetObject("ico-ecommerce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ico_ecommerce__1_ {
            get {
                object obj = ResourceManager.GetObject("ico-ecommerce (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_256 {
            get {
                object obj = ResourceManager.GetObject("icon_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_carritus_twitter {
            get {
                object obj = ResourceManager.GetObject("icon_carritus_twitter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_cart {
            get {
                object obj = ResourceManager.GetObject("icon-cart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_contas {
            get {
                object obj = ResourceManager.GetObject("icon-contas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_pague_contas {
            get {
                object obj = ResourceManager.GetObject("icon-pague-contas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icone_Amigo_Homem {
            get {
                object obj = ResourceManager.GetObject("Icone-Amigo_Homem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icone_Amigo_Homem1 {
            get {
                object obj = ResourceManager.GetObject("Icone-Amigo_Homem1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_cadastro {
            get {
                object obj = ResourceManager.GetObject("icone_cadastro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icone_cadastro1 {
            get {
                object obj = ResourceManager.GetObject("icone_cadastro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconmenos {
            get {
                object obj = ResourceManager.GetObject("iconmenos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icovend {
            get {
                object obj = ResourceManager.GetObject("icovend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JasperReports {
            get {
                object obj = ResourceManager.GetObject("JasperReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap JPortugall_icon_wardrobe {
            get {
                object obj = ResourceManager.GetObject("JPortugall_icon_wardrobe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap login {
            get {
                object obj = ResourceManager.GetObject("login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lupa {
            get {
                object obj = ResourceManager.GetObject("lupa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pdbaixa {
            get {
                object obj = ResourceManager.GetObject("pdbaixa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pres {
            get {
                object obj = ResourceManager.GetObject("pres", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Recycle_Bin_Full {
            get {
                object obj = ResourceManager.GetObject("Recycle_Bin_Full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Remove_User_80_icon_icons {
            get {
                object obj = ResourceManager.GetObject("Remove_User-80_icon-icons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ROPAAA {
            get {
                object obj = ResourceManager.GetObject("ROPAAA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ROPAAA1 {
            get {
                object obj = ResourceManager.GetObject("ROPAAA1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s0icon_9b108869337b958c857b09b89cffabf4 {
            get {
                object obj = ResourceManager.GetObject("s0icon-9b108869337b958c857b09b89cffabf4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s0icon_9b108869337b958c857b09b89cffabf41 {
            get {
                object obj = ResourceManager.GetObject("s0icon-9b108869337b958c857b09b89cffabf41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sdadsasdas {
            get {
                object obj = ResourceManager.GetObject("sdadsasdas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_copy_14117903638kgn4 {
            get {
                object obj = ResourceManager.GetObject("search-copy-14117903638kgn4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search_Folder_icon {
            get {
                object obj = ResourceManager.GetObject("Search-Folder-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_shot_interface_symbol_with_a_magnifier_tool_318_55166 {
            get {
                object obj = ResourceManager.GetObject("search-shot-interface-symbol-with-a-magnifier-tool_318-55166", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap search_var_flat {
            get {
                object obj = ResourceManager.GetObject("search-var-flat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopping_basket_add256_24909 {
            get {
                object obj = ResourceManager.GetObject("shopping-basket-add256_24909", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Shopping_cart_remove_icon {
            get {
                object obj = ResourceManager.GetObject("Shopping-cart-remove-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopping_icon {
            get {
                object obj = ResourceManager.GetObject("shopping-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sinal_ {
            get {
                object obj = ResourceManager.GetObject("sinal+", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sinal_1 {
            get {
                object obj = ResourceManager.GetObject("sinal+1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sinal_de_mais_em_um_circulo_preto_318_41856 {
            get {
                object obj = ResourceManager.GetObject("sinal-de-mais-em-um-circulo-preto_318-41856", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap solucao_vendas_icon {
            get {
                object obj = ResourceManager.GetObject("solucao-vendas-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stock_illustration_68014971_vector_flat_magnifying_glass_icon {
            get {
                object obj = ResourceManager.GetObject("stock-illustration-68014971-vector-flat-magnifying-glass-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_add {
            get {
                object obj = ResourceManager.GetObject("user_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wood_263802_960_720 {
            get {
                object obj = ResourceManager.GetObject("wood-263802_960_720", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
